
#define DIRECTIVE   0
#define OP_MULTIPLE -1

assemblers_t assemblers[] = {
    {"ADDF4",   OP_ADDF4,      assfn(CODE_OP)   },
    {"ADDI3",   OP_ADD3,       assfn(CODE_OP)   },
    {"ADDI4",   OP_ADD4,       assfn(CODE_OP)   },
    {"ADDP3",   OP_ADD3,       assfn(CODE_OP)   },
    {"ADDRESS", DIRECTIVE,     assfn(ADDRESS)   },
    {"ADDRF",   OP_LOCAL,      assfn(ADDRF)     },
    {"ADDRGP3", OP_CONSTGP3,   assfn(CODE_24BIT)},
    {"ADDRL",   OP_LOCAL,      assfn(ADDRL)     },
    {"ADDU3",   OP_ADD3,       assfn(CODE_OP)   },
    {"ADDU4",   OP_ADD4,       assfn(CODE_OP)   },
    {"ALIGN",   DIRECTIVE,     assfn(ALIGN)     },
    {"ARGF",    OP_ARG4,       assfn(ARG4)      },
    {"ARGI3",   OP_ARG3,       assfn(ARG3)      },
    {"ARGI4",   OP_ARG4,       assfn(ARG4)      },
    {"ARGP",    OP_ARG3,       assfn(ARG3)      },
    {"ARGU3",   OP_ARG3,       assfn(ARG3)      },
    {"ARGU4",   OP_ARG4,       assfn(ARG4)      },
    {"ASGNB",   OP_BLOCK_COPY, assfn(CODE_24BIT)},
    {"ASGNF4",  OP_STORE4,     assfn(CODE_OP)   },
    {"ASGNI1",  OP_STORE1,     assfn(CODE_OP)   },
    {"ASGNI2",  OP_STORE2,     assfn(CODE_OP)   },
    {"ASGNI3",  OP_STORE3,     assfn(CODE_OP)   },
    {"ASGNI4",  OP_STORE4,     assfn(CODE_OP)   },
    {"ASGNP3",  OP_STORE3,     assfn(CODE_OP)   },
    {"ASGNP4",  OP_STORE4,     assfn(CODE_OP)   },
    {"ASGNU1",  OP_STORE1,     assfn(CODE_OP)   },
    {"ASGNU2",  OP_STORE2,     assfn(CODE_OP)   },
    {"ASGNU3",  OP_STORE3,     assfn(CODE_OP)   },
    {"ASGNU4",  OP_STORE4,     assfn(CODE_OP)   },
    {"BANDI3",  OP_BAND3,      assfn(CODE_OP)   },
    {"BANDI4",  OP_BAND4,      assfn(CODE_OP)   },
    {"BANDU3",  OP_BAND3,      assfn(CODE_OP)   },
    {"BANDU4",  OP_BAND4,      assfn(CODE_OP)   },
    {"BCOMI3",  OP_BCOM3,      assfn(CODE_OP)   },
    {"BCOMI4",  OP_BCOM4,      assfn(CODE_OP)   },
    {"BCOMU3",  OP_BCOM3,      assfn(CODE_OP)   },
    {"BCOMU4",  OP_BCOM4,      assfn(CODE_OP)   },
    {"BORI3",   OP_BOR3,       assfn(CODE_OP)   },
    {"BORI4",   OP_BOR4,       assfn(CODE_OP)   },
    {"BORU4",   OP_BOR4,       assfn(CODE_OP)   },
    {"BSS",     DIRECTIVE,     assfn(BSS)       },
    {"BXORI3",  OP_BXOR3,      assfn(CODE_OP)   },
    {"BXORI4",  OP_BXOR4,      assfn(CODE_OP)   },
    {"BXORU4",  OP_BXOR4,      assfn(CODE_OP)   },
    {"BYTE",    DIRECTIVE,     assfn(BYTE)      },
    {"CALLF4",  OP_CALL,       assfn(CALL)      },
    {"CALLI3",  OP_CALL,       assfn(CALL)      },
    {"CALLI4",  OP_CALL,       assfn(CALL)      },
    {"CALLP3",  OP_CALL,       assfn(CALL)      },
    {"CALLU3",  OP_CALL,       assfn(CALL)      },
    {"CALLU4",  OP_CALL,       assfn(CALL)      },
    {"CALLV",   OP_CALL,       assfn(CALL)      },
    {"CNSTF4",  OP_CONSTs4,    assfn(CODE_FLOAT)},
    {"CNSTI1",  OP_CONSTs1,    assfn(CODE_8BIT) },
    {"CNSTI2",  OP_CONSTs2,    assfn(CODE_16BIT)},
    {"CNSTI3",  OP_CONSTs3,    assfn(CODE_24BIT)},
    {"CNSTI4",  OP_CONSTs4,    assfn(CODE_32BIT)},
    {"CNSTP3",  OP_CONSTP3,    assfn(CODE_24BIT)},
    {"CNSTU1",  OP_CONSTs1,    assfn(CODE_8BIT) },
    {"CNSTU2",  OP_CONSTs2,    assfn(CODE_16BIT)},
    {"CNSTU3",  OP_CONSTs3,    assfn(CODE_24BIT)},
    {"CNSTU4",  OP_CONSTs4,    assfn(CODE_32BIT)},
    {"CODE",    DIRECTIVE,     assfn(CODE)      },
    {"CVFI3",   OP_CF4I3,      assfn(CODE_OP)   },
    {"CVFI4",   OP_CF4I4,      assfn(CODE_OP)   },
    {"CVIF4",   OP_MULTIPLE,   assfn(CODE_CIxF4)},
    {"CVII1",   OP_IGNORE,     assfn(CODE_CIxI1)},
    {"CVII2",   OP_MULTIPLE,   assfn(CODE_CIxI2)},
    {"CVII3",   OP_MULTIPLE,   assfn(CODE_CIxI3)}, /* extend sign Ix to I3*/
    {"CVII4",   OP_MULTIPLE,   assfn(CODE_CIxI4)},
    {"CVIU3",   OP_IGNORE,     assfn(CODE_CIxU3)},
    {"CVIU4",   OP_IGNORE,     assfn(CODE_CIxU4)},
    {"CVPU3",   OP_IGNORE,     assfn(COMMENT)   },
    {"CVUI3",   OP_MULTIPLE,   assfn(CODE_CUxI3)},
    {"CVUI4",   OP_IGNORE,     assfn(COMMENT)   },
    {"CVUP3",   OP_IGNORE,     assfn(COMMENT)   },
    {"CVUU1",   OP_IGNORE,     assfn(COMMENT)   },
    {"CVUU2",   OP_IGNORE,     assfn(CODE_CUxU2)},
    {"CVUU3",   OP_IGNORE,     assfn(CODE_CUxU3)},
    {"CVUU4",   OP_IGNORE,     assfn(CODE_CUxU4)},
    {"DATA",    DIRECTIVE,     assfn(DATA)      },
    {"DIVF4",   OP_DIVF4,      assfn(CODE_OP)   },
    {"DIVI3",   OP_DIVI3,      assfn(CODE_OP)   },
    {"DIVI4",   OP_DIVI4,      assfn(CODE_OP)   },
    {"DIVU3",   OP_DIVU3,      assfn(CODE_OP)   },
    {"DIVU4",   OP_DIVU4,      assfn(CODE_OP)   },
    {"ENDPROC", OP_MULTIPLE,   assfn(ENDPROC)   },
    {"EQF4",    OP_EQF4,       assfn(CODE_24BIT)},
    {"EQI3",    OP_EQ3,        assfn(CODE_24BIT)},
    {"EQI4",    OP_EQ4,        assfn(CODE_24BIT)},
    {"EQU3",    OP_EQ3,        assfn(CODE_24BIT)},
    {"EQU4",    OP_EQ4,        assfn(CODE_24BIT)},
    {"EQU",     DIRECTIVE,     assfn(EQU)       }, /* this must come after the other EQ.. operations */
    {"EXPORT",  DIRECTIVE,     assfn(COMMENT)   },
    {"FILE",    DIRECTIVE,     assfn(COMMENT)   },
    {"GEF4",    OP_GEF4,       assfn(CODE_24BIT)},
    {"GEI3",    OP_GEI3,       assfn(CODE_24BIT)},
    {"GEI4",    OP_GEI4,       assfn(CODE_24BIT)},
    {"GEU3",    OP_GEU3,       assfn(CODE_24BIT)},
    {"GEU4",    OP_GEU4,       assfn(CODE_24BIT)},
    {"GTF4",    OP_GTF4,       assfn(CODE_24BIT)},
    {"GTI3",    OP_GTI3,       assfn(CODE_24BIT)},
    {"GTI4",    OP_GTI4,       assfn(CODE_24BIT)},
    {"GTU3",    OP_GTU3,       assfn(CODE_24BIT)},
    {"GTU4",    OP_GTU4,       assfn(CODE_24BIT)},
    {"IMPORT",  DIRECTIVE,     assfn(COMMENT)   },
    {"INDIRB",  OP_IGNORE,     assfn(COMMENT)   },
    {"INDIRF4", OP_LOAD4,      assfn(CODE_OP)   },
    {"INDIRI1", OP_LOAD1,      assfn(CODE_OP)   },
    {"INDIRI2", OP_LOAD2,      assfn(CODE_OP)   },
    {"INDIRI3", OP_LOAD3,      assfn(CODE_OP)   },
    {"INDIRI4", OP_LOAD4,      assfn(CODE_OP)   },
    {"INDIRP3", OP_LOAD3,      assfn(CODE_OP)   },
    {"INDIRP4", OP_LOAD4,      assfn(CODE_OP)   },
    {"INDIRU1", OP_LOAD1,      assfn(CODE_OP)   },
    {"INDIRU2", OP_LOAD2,      assfn(CODE_OP)   },
    {"INDIRU3", OP_LOAD3,      assfn(CODE_OP)   },
    {"INDIRU4", OP_LOAD4,      assfn(CODE_OP)   },
    {"JUMPV",   OP_JUMP,       assfn(CODE_OP)   },
    {"LABEL",   DIRECTIVE,     assfn(LABEL)     },
    {"LEF4",    OP_LEF4,       assfn(CODE_24BIT)},
    {"LEI3",    OP_LEI3,       assfn(CODE_24BIT)},
    {"LEI4",    OP_LEI4,       assfn(CODE_24BIT)},
    {"LEU3",    OP_LEU3,       assfn(CODE_24BIT)},
    {"LEU4",    OP_LEU4,       assfn(CODE_24BIT)},
    {"LINE",    DIRECTIVE,     assfn(COMMENT)   },
    {"LIT",     DIRECTIVE,     assfn(LIT)       },
    {"LSHI3",   OP_LSH3,       assfn(CODE_OP)   },
    {"LSHI4",   OP_LSH4,       assfn(CODE_OP)   },
    {"LSHU3",   OP_LSH3,       assfn(CODE_OP)   },
    {"LSHU4",   OP_LSH4,       assfn(CODE_OP)   },
    {"LTF4",    OP_LTF4,       assfn(CODE_24BIT)},
    {"LTI3",    OP_LTI3,       assfn(CODE_24BIT)},
    {"LTI4",    OP_LTI4,       assfn(CODE_24BIT)},
    {"LTU3",    OP_LTU3,       assfn(CODE_24BIT)},
    {"LTU4",    OP_LTU4,       assfn(CODE_24BIT)},
    {"MODI3",   OP_MODI3,      assfn(CODE_OP)   },
    {"MODI4",   OP_MODI4,      assfn(CODE_OP)   },
    {"MODU3",   OP_MODU3,      assfn(CODE_OP)   },
    {"MODU4",   OP_MODU4,      assfn(CODE_OP)   },
    {"MULF4",   OP_MULF4,      assfn(CODE_OP)   },
    {"MULI3",   OP_MULI3,      assfn(CODE_OP)   },
    {"MULI4",   OP_MULI4,      assfn(CODE_OP)   },
    {"MULU3",   OP_MULU3,      assfn(CODE_OP)   },
    {"MULU4",   OP_MULU4,      assfn(CODE_OP)   },
    {"NEF4",    OP_NEF4,       assfn(CODE_24BIT)},
    {"NEGF4",   OP_NEGF4,      assfn(CODE_OP)   },
    {"NEGI3",   OP_NEGI3,      assfn(CODE_OP)   },
    {"NEGI4",   OP_NEGI4,      assfn(CODE_OP)   },
    {"NEI3",    OP_NE3,        assfn(CODE_24BIT)},
    {"NEI4",    OP_NE4,        assfn(CODE_24BIT)},
    {"NEU3",    OP_NE3,        assfn(CODE_24BIT)},
    {"NEU4",    OP_NE4,        assfn(CODE_24BIT)},
    {"POP",     OP_POP,        assfn(CODE_OP)   },
    {"PROC",    OP_ENTER,      assfn(PROC)      },
    {"RET",     OP_LEAVE,      assfn(RET)       },
    {"RSHI3",   OP_RSHI3,      assfn(CODE_OP)   },
    {"RSHI4",   OP_RSHI4,      assfn(CODE_OP)   },
    {"RSHU3",   OP_RSHU3,      assfn(CODE_OP)   },
    {"RSHU4",   OP_RSHU4,      assfn(CODE_OP)   },
    {"SKIP",    DIRECTIVE,     assfn(SKIP)      },
    {"SUBF4",   OP_SUBF4,      assfn(CODE_OP)   },
    {"SUBI3",   OP_SUB3,       assfn(CODE_OP)   },
    {"SUBI4",   OP_SUB4,       assfn(CODE_OP)   },
    {"SUBP3",   OP_SUB4,       assfn(CODE_OP)   },
    {"SUBU3",   OP_SUB4,       assfn(CODE_OP)   },
    {"SUBU4",   OP_SUB4,       assfn(CODE_OP)   },
};
